name: DiscordInGameConfig
version: 1.1.0
main: pro.plugin.discordingameconfig.DiscordInGameConfig
api-version: '1.21'
depend: [ProtocolLib]
commands:
  discordconfig:
    aliases: [dcconfig, dcc]
    permission: discordinlet.admin